payment/urls.py
from django.urls import path
from . import  views 


app_name = 'payment'  
urlpatterns = [
    path('', views.item_list, name='item_list'),  
    path('item/<int:item_id>/', views.item_detail, name='item_detail'),
    path('buy/<int:item_id>/', views.CreateCheckoutSessionView, name='create_checkout_session'),
    path('payment-success/', views.payment_success, name='payment_success'),
    path('payment-cancel/', views.payment_cancel, name='payment_cancel'),
    path('add-to-cart/<int:item_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.cart_view, name='cart'),
    path('buy_order/', views.CreateCheckoutForOrderView, name='buy_order'), 
    path('stripe-payment-intent/<int:item_id>/',views.create_payment_intent,name='payment_intent') 
    # path('cart/', views.cart_view, name='cart_view
]

test_payment_system_task/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('payment.urls')),  
    path('admin/', admin.site.urls),
]

payment/models.py
from django.db import models

# Create your models here.
class Discount(models.Model):
    code = models.CharField(max_length=50, unique=True,default='NO_DISCOUNT')
    percentage = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.code
    
class Tax(models.Model):
    type = models.CharField(max_length=50)
    percentage = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return self.type

class Item(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    currency = models.CharField(max_length=4,default='usd')

    def __str__(self):
        return self.name
    
class OrderItem(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    is_ordered= models.BooleanField(default=False)

class Order(models.Model):
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    discount = models.ForeignKey(Discount, on_delete=models.SET_NULL, null=True, blank=True)
    tax = models.ForeignKey(Tax, on_delete=models.SET_NULL, null=True, blank=True)

payment/views.py
from decimal import ROUND_HALF_UP, Decimal
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from .models import Item, Order, OrderItem, Discount, Tax
from django.shortcuts import redirect,get_object_or_404
# Create your views here.
from django.shortcuts import redirect
from django.conf import settings
from django.contrib.auth.decorators import login_required
import stripe
import requests



@csrf_exempt
def create_payment_intent(request, item_id):
    # Retrieve the item by ID
    item = get_object_or_404(Item, id=item_id)
    currency = item.currency

    # Set the appropriate Stripe secret key based on currency
    stripe.api_key = settings.STRIPE_SECRET_KEY.get(currency)

    if stripe.api_key is None:
        return JsonResponse({'error': f'Stripe key not found for currency "{currency}"'}, status=500)

    try:
        # Create the payment intent
        intent = stripe.PaymentIntent.create(
            amount=int(item.price * 100),  # price in cents
            currency=currency,
            payment_method_types=['card'],
            metadata={
                'item_id': str(item.id),
                'item_name': item.name,
                'currency': currency,
            },
        )

        context = {
            'item': item,
            'clientSecret': intent.client_secret,
            'publishableKey': settings.STRIPE_PUBLISHABLE_KEY.get(currency),
        }

        return render(request, 'payment/intent_payment.html', context)

    except stripe.error.StripeError as e:
        # Handle Stripe-specific errors
        return JsonResponse({'error': str(e)}, status=400)

    except Exception as e:
        # Handle unexpected errors
        return JsonResponse({'error': f'Unexpected error: {str(e)}'}, status=500)# @login_required
    

def CreateCheckoutSessionView(request, item_id):
    item= Item.objects.get(id=item_id)
    selected_currency = request.GET.get('currency', item.currency.lower())
    currency = selected_currency
    if currency=='eur':
        response = requests.get("https://api.exchangerate.host/convert", params={
        "access_key":settings.ACCESS_KEY,
        "from": "USD",
        "to": "EUR",
        "amount": item.price
    })
        data=response.json()
        if not data.get("result"):
            raise Exception(f"Currency conversion failed: {data}")
        print (data)
        price=data['result']
    else:
        price=item.price
    stripe.api_key = settings.STRIPE_SECRET_KEY[currency]
    YOUR_DOMAIN = f"{request.scheme}://{request.get_host()}"
    
    checkout_session = stripe.checkout.Session.create(
        payment_method_types=['card'],
        line_items=[
            {
                'price_data': {
                    'currency': currency,
                    'unit_amount': int(price*100),
                    'product_data': {
                        'name': item.name
                        # 'images': [f'{item.image}']
                    },
                },
                'quantity': 1,
            },
        ],
        metadata = {
            'item_id': item_id,
            # 'user_email': request.user.email
        },
        
        mode='payment',

        success_url=YOUR_DOMAIN + f'/payment-success/',
        cancel_url=YOUR_DOMAIN + f'/payment-cancel',
    )

    return redirect(checkout_session.url)


def CreateCheckoutForOrderView(request):
    stripe.api_key = settings.STRIPE_SECRET_KEY['usd']
    total_price = 0
    order_items = OrderItem.objects.all()
    for order in order_items:
        total_price += order.item.price * order.quantity
    tax= Tax.objects.first()  
    discount = Discount.objects.first() 
    order = Order.objects.create(total_price=total_price, tax=tax, discount=discount)
    tax_amount=((order.tax.percentage/100) * order.total_price)
    print(tax_amount)
    discount_amount = (order.discount.percentage/100)
    YOUR_DOMAIN = f"{request.scheme}://{request.get_host()}"
    checkout_session = stripe.checkout.Session.create(
        payment_method_types=['card'],
        line_items=[
            {
                'price_data': {
                    'currency': 'usd',
                    'unit_amount': int(order.total_price * 100),
                    'product_data': {
                        'name': 'Your Order',
                        # 'tax_code': 'txcd_99999999'
                    },
                },
                'quantity': 1,
            },
             {
                'price_data': {
                    'currency': 'usd',
                    'unit_amount': int(((order.tax.percentage/100+1) * order.total_price*100)-(order.total_price * 100)),
                    'product_data': {
                        'name': 'Tax amount',
                        # 'tax_code': 'txcd_99999999'
                    },
                },
                'quantity': 1,

            },
        ],
        discounts=[{
            'coupon': discount.code if discount else None
        }],

        metadata = {
            'item_id': order.id,
            # 'user_email': request.user.email
        },
        
        mode='payment',

        success_url=YOUR_DOMAIN + f'/payment-success/',
        cancel_url=YOUR_DOMAIN + f'/payment-cancel',
    )
    order.delete()
    return redirect(checkout_session.url)


def payment_success(request):
    order_items=OrderItem.objects.all()
    for order in order_items:
        order.delete()
    return render(request, 'payment/payment_success.html')

def payment_cancel(request):
    return render(request, 'payment/payment_cancel.html')


def item_list(request):
    items = Item.objects.all()
    return render(request, 'payment/items_list.html', {'items': items})

def item_detail(request, item_id):
    item = Item.objects.get(id=item_id)
    return render(request, 'payment/item_details.html', {'item': item})

def add_to_cart(request, item_id):
    item = Item.objects.get(id=item_id)
    order_item, created = OrderItem.objects.get_or_create(item=item)
    if created:
        order_item.quantity = 1
    else:
        order_item.quantity += 1
    order_item.save()
    return redirect('payment:item_detail', item_id=item.id)

def cart_view(request):
    order_items = OrderItem.objects.all()
    total_price = sum(order_item.item.price * order_item.quantity for order_item in order_items)
    return render(request, 'payment/cart.html', {'order_items': order_items, 'total_price': total_price})

payment/templates/payment/cart.html
{% extends "base.html" %}

{%block content %}
{% for order in order_items %}
{% if order.item.name %}
{{ order.item.name }} - Quantity: {{ order.quantity }}
<br>
{% endif %}
{% endfor %}
{%if not order_items %}
<p>Your cart is empty.</p>
{% else %}
<a href="{% url 'payment:buy_order' %}"><button class='btn btn-primary' style='margin: 5px;'>Buy</button></a>
{% endif %}
<div>
    <a href="{% url 'payment:item_list' %}"><button class='btn btn-primary' style='margin: 5px;'>Back to Item List</button></a>
</div>
{% endblock %}

payment/templates/payment/intent_payment.html
<script src="https://js.stripe.com/v3/"></script>

<h2>Pay for {{ item.name }} ({{ item.price }} usd)</h2>

<form id="payment-form">
  <div id="card-element"></div>
  <button type="submit">Pay</button>
  <div id="error-message"></div>
</form>

<script>
  const stripe = Stripe("{{ publishableKey }}");
  const clientSecret = "{{ clientSecret }}";

  const elements = stripe.elements();
  const card = elements.create("card");
  card.mount("#card-element");

  const form = document.getElementById("payment-form");
  form.addEventListener("submit", async (event) => {
    event.preventDefault();

    const { error, paymentIntent } = await stripe.confirmCardPayment(clientSecret, {
      payment_method: {
        card: card
      }
    });

    if (error) {
      document.getElementById("error-message").textContent = error.message;
    } else {
      window.location.href = "/payment-success/";
    }
  });
</script>

payment/templates/payment/item_details.html
{% extends "base.html" %}
{% block content %}
<h1>{{ item.name }}</h1>
<p>{{ item.description }}</p>
<p>Price: ${{ item.price }}</p>
<a href="{% url 'payment:create_checkout_session' item.id %}?currency=usd"> <button class='btn btn-primary' style='margin: 5px;'>Buy in usd</button></a>
<a href="{% url 'payment:create_checkout_session' item.id %}?currency=eur"> <button class='btn btn-primary' style='margin: 5px;'>Buy in eur</button></a>
<a href="{% url 'payment:payment_intent' item.id %}"> <button class='btn btn-primary' style='margin: 5px;'>Buy different payment method</button></a>

<div><a href="{% url 'payment:item_list' %}"><button class='btn btn-primary' style='margin: 5px;'>Back to Item List</button></a></div>
<div><a href="{% url 'payment:add_to_cart' item.id %}"><button class='btn btn-primary' style='margin: 5px;'>Add to Cart</button></a></div>
<div><a href="{% url 'payment:cart' %}"><button class='btn btn-primary' style='margin: 5px;'>View Cart</button></a></div>
{% endblock content %}

payment/templates/payment/items_list.html
{% extends "base.html" %}
{% block content %}
<h1>Item List</h1>
<ul>
    {% for item in items %}
     <li>
        <h2> <a href="{% url 'payment:item_detail' item.id %}">{{item.name}}</a></h2>   
        <p>Price: ${{ item.price }}</p>
     </li>
    {% endfor %}
</ul>
<div>
    <a href="{% url 'payment:cart' %}"><button class='btn btn-primary'>View Cart</button></a>
{% endblock content %}

payment/templates/payment/payment_cancel.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Payment Success</title>
</head>
<body>
    <h1>Payment Canceled</h1>
    <p>Your payment was not successful.</p>
    <a href = "{% url 'payment:item_list' %}">View Items</a>
</body>
</html>

payment/templates/payment/payment_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Payment Success</title>
</head>
<body>
    <h1>Payment Successful</h1>
    <p>Thank you for your payment!</p>
    <a href = "{% url 'payment:item_list' %}">View Items</a>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}My Shop{% endblock %}</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <header>
        {% comment %} <h1>Welcome to My Shop</h1>
        <nav>
            <ul>
                <li><a href="{% url 'payment:item_list' %}">Items</a></li>
            </ul>
        </nav> {% endcomment %}
    </header>
    <main>
        {% block content %}
        {% endblock content %}
    </main>
</body>
</html>